### ISSUE TITLE
can we use php into the code ?

### ISSUE THREAD

**Issue by cfconsultancy** [martyf/tinymce-5-plugin-with-dialog#1]
How about using php to fill the select box ? An url ?

**Comment by martyf** [comment]
Most definitely. This example purely shows how to create a Dialog, as well as "block" it while something happens (i.e. a call to the server to get data).

This is exactly why I wrote the demo - I need to get new options from the server and display them in the dialog. 

But given you don't have access to the rest of my application, how I do that server call for _my_ app is irrelevant to the concepts in this demo - and will no doubt be different to how you call the server for _your_ app.

If you look at the _onAction function in the plugin.js file, you'll see there is a setTimout call that populates the select box with new options.

That setTimeout call would be replaced with your call to the server - maybe it's a GET, maybe a POST, maybe you need auth, etc - so many variables come in to play here, so for simplicity, we're simulating a call to show the concepts - i.e. a 1 second delay - but using setTimeout to achieve the delay so we can see the block, update, redial and unblock in action.

The setTimeout call is purely used in this demo to illustrate:
- blocking while "something" happens (in this case, a 1 second delay)
- updating the options
- redialing to re-build the dialog
- unblocking the dialog

The "something" mentioned there can be your server side call. Maybe you're calling an end point to get options. Maybe you'll pass a URL (such as a YouTube video) and the server will call the YouTube API to get the title and a thumbnail. Whatever you need can happen there - that's up to you and your application though.

When your "something" is finished (i.e. you've got the data back from the server, and you've updated your options), you then would redial and unblock the dialog again and you'll have the updated options from the server.

So instead of the "setTimeout" that you see there, you'll do your GET or POST call (or whatever you need to do) and when that is finished (such as a "complete" function, depending on how you're calling the server) you would update your options, redial, and unblock.

Does that make sense?

**Comment by gtraxx** [comment]
Hi, So "file" is no longer available in tinymce 5 ?
```
editor.windowManager.open({
                title: "Test",
                file: url + "/test.php"
            });
```

**Comment by martyf** [comment]
That is correct, unfortunately. 

There’s an open issue regarding this on the TinyMCE github:
https://github.com/tinymce/tinymce/issues/4786

**Comment by gtraxx** [comment]
Thanks :) 
I will be patient to update my plugins

```
Error: Errors: 
Failed path: (dialog)
Could not find valid *strict* value for "body" in {
   "title": "test",
  "file": "/tinymce/plugins/test/test.html"
},Failed path: (dialog)
Could not find valid *strict* value for "buttons" in {
  "title": "test",
  "file": "/tinymce/plugins/test/test.html"
}

Input object: {
   "title": "test",
  "file": "/tinymce/plugins/test/test.html"
}
```

**Comment by martyf** [comment]
Don't forget to check out the new UI components - my plugins feel fantastic being built using Tiny's UI components.

The Tiny documentation shows you the core dialog setup and architecture:
https://www.tiny.cloud/docs/ui-components/dialog/
https://www.tiny.cloud/docs/ui-components/dialogcomponents/

All except those that absolutely required external files (such as "file").

**Comment by gtraxx** [comment]
Hi @martyf , I tested a simple code (from new dialog) but it does not work 
```
editor.windowManager.open({
                    title: 'My html dialog',
                    url: 'youtube.html',
                    width: 700,
                    height: 600
                });
```

here is the error in the console

```
Error: Errors: 
Failed path: (dialog)
Could not find valid *strict* value for "body" in {
  "title": "My html dialog",
  "url": "youtube.html",
  "width": 700,
  "height": 600
},Failed path: (dialog)
Could not find valid *strict* value for "buttons" in {
  "title": "My html dialog",
  "url": "youtube.html",
  "width": 700,
  "height": 600
}

Input object: {
  "title": "My html dialog",
  "url": "youtube.html",
  "width": 700,
  "height": 600
}

```

**Comment by martyf** [comment]
Hey @gtraxx check a few comments above for a link to the Tiny issue about this - at this stage there is no way to embed a HTML page like you can in v4 and v3.

**Comment by gtraxx** [comment]
Thanks :)
I will analyze to convert my plugin with V5 API without external file but many will no longer be possible without the use of an external file

**Comment by martyf** [comment]
Tiny are aware of this roadblock and are still determining the best way forward. As I find out more, I’ll extend this repo and post about it on my blog.

**Comment by gtraxx** [comment]
Thanks :)

**Comment by martyf** [comment]
Hey @gtraxx, URL Dialog is a new UI Component in TinyMCE 5 - I've updated the repository with two new plugins that break down how it all works.

You can read more on my [website](https://www.martyfriedel.com/blog/tinymce-5-url-dialog-component-and-window-messaging)
You can see working demos at [https://tinymce.martyfriedel.com/](https://tinymce.martyfriedel.com/)

**Comment by gtraxx** [comment]
Hi, thanks, I will test with the update of my plugin :)
Did they update the documentation ?

**Comment by martyf** [comment]
Yes, all documentation has been updated.

When going from 4 to 5, also check the documentation for notes of changes too - there are a few different calls

URL Dialog:
https://www.tiny.cloud/docs/ui-components/urldialog/

Migration from 4 to 5:
https://www.tiny.cloud/docs/migration-from-4x/
